apiVersion: v1
kind: Secret
metadata:
  name: {{ include "websocket-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "websocket-manager.labels" . | nindent 4 }}
type: Opaque
data:
  appsettings.json: {{ toJson .Values.secret | b64enc | quote}}
