// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dialogs/subscriptions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DialogSubscriptions"
                ],
                "summary": "Clear dialog subscriptions",
                "parameters": [
                    {
                        "description": "CreateDialogSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ClearDialogSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/dialogs/subscriptions/clear": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DialogSubscriptions"
                ],
                "summary": "Clear all dialog subscriptions for specific user",
                "parameters": [
                    {
                        "description": "ClearDialogSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ClearDialogSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/dialogs/subscriptions/remove": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DialogSubscriptions"
                ],
                "summary": "Remove set of user dialogs for specific user",
                "parameters": [
                    {
                        "description": "RemoveDialogSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.RemoveDialogSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/user-groups/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Publish message to user group",
                "parameters": [
                    {
                        "description": "PublishMessageToUserGroup",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PublishMessageToUserGroup"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/user-groups/subscriptions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserGroupSubscriptions"
                ],
                "summary": "Create user group subscriptions",
                "parameters": [
                    {
                        "description": "CreateUserGroupSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.CreateUserGroupSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/user-groups/subscriptions/clear": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserGroupSubscriptions"
                ],
                "summary": "Clear user group subscriptions",
                "parameters": [
                    {
                        "description": "ClearUserGroupSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ClearUserGroupSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/user-groups/subscriptions/remove": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserGroupSubscriptions"
                ],
                "summary": "Remove user group subscriptions",
                "parameters": [
                    {
                        "description": "RemoveUserGroupSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.RemoveUserGroupSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/users/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Publish message to users",
                "parameters": [
                    {
                        "description": "PublishMessageToUsers",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PublishMessageToUsers"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "apierrors.PublicErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "apierrors.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                }
            }
        },
        "apierrors.ValidationErrorsResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apierrors.ValidationErrorResponse"
                    }
                }
            }
        },
        "forms.ClearDialogSubscriptions": {
            "type": "object",
            "required": [
                "initiatorId"
            ],
            "properties": {
                "initiatorId": {
                    "type": "integer"
                }
            }
        },
        "forms.ClearUserGroupSubscriptions": {
            "type": "object",
            "required": [
                "groupId"
            ],
            "properties": {
                "groupId": {
                    "type": "integer"
                }
            }
        },
        "forms.CreateUserGroupSubscriptions": {
            "type": "object",
            "required": [
                "groupId",
                "userIds"
            ],
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.PublishMessageToUserGroup": {
            "type": "object",
            "required": [
                "groupId",
                "message"
            ],
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "message": {
                    "type": "object"
                }
            }
        },
        "forms.PublishMessageToUsers": {
            "type": "object",
            "required": [
                "message",
                "userIds"
            ],
            "properties": {
                "message": {
                    "type": "object"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.RemoveDialogSubscriptions": {
            "type": "object",
            "required": [
                "initiatorId",
                "userIds"
            ],
            "properties": {
                "initiatorId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.RemoveUserGroupSubscriptions": {
            "type": "object",
            "required": [
                "groupId",
                "userIds"
            ],
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Websocket manager API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
