// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/channel-subscriptions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChannelSubscriptions"
                ],
                "summary": "Create channel subscriptions",
                "parameters": [
                    {
                        "description": "CreateChannelSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.CreateChannelSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/channel-subscriptions/batch-remove": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChannelSubscriptions"
                ],
                "summary": "Remove channel subscriptions",
                "parameters": [
                    {
                        "description": "RemoveChannelSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.RemoveChannelSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/channel-subscriptions/channels/:channelId": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChannelSubscriptions"
                ],
                "summary": "Clear channel subscriptions by channel id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Channel id",
                        "name": "channelId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/channels/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChannelSubscriptions"
                ],
                "summary": "Publish message to channel",
                "parameters": [
                    {
                        "description": "PublishMessageToChannel",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PublishMessageToChannel"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/dialog-subscriptions/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DialogSubscriptions"
                ],
                "summary": "Publish message to interlocutors",
                "parameters": [
                    {
                        "description": "PublishMessageToInterlocutorsRequest",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PublishMessageToInterlocutors"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/dialogs-subscriptions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DialogSubscriptions"
                ],
                "summary": "Create dialog subscriptions",
                "parameters": [
                    {
                        "description": "CreateDialogSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.CreateDialogSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/dialogs-subscriptions/batch-remove": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DialogSubscriptions"
                ],
                "summary": "Remove set of user dialogs for specific user",
                "parameters": [
                    {
                        "description": "RemoveDialogSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.RemoveDialogSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/group-subscriptions/groups/{groupId}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupSubscriptions"
                ],
                "summary": "Clear group subscriptions by group id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Group id",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/groups/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupSubscriptions"
                ],
                "summary": "Publish message to group",
                "parameters": [
                    {
                        "description": "PublishMessageToGroup",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PublishMessageToGroup"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/groups/subscriptions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupSubscriptions"
                ],
                "summary": "Create group subscriptions",
                "parameters": [
                    {
                        "description": "CreateGroupSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.CreateGroupSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/groups/subscriptions/remove": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupSubscriptions"
                ],
                "summary": "Remove group subscriptions",
                "parameters": [
                    {
                        "description": "RemoveGroupSubscriptions",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.RemoveGroupSubscriptions"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/users/:initiatorId/dialog-subscriptions": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DialogSubscriptions"
                ],
                "summary": "Clear all dialog subscriptions by initiatorId",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Initiator id",
                        "name": "initiatorId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/users/:userId/channel-subscriptions": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChannelSubscriptions"
                ],
                "summary": "Clear channel subscriptions by user id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/users/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Publish message to users",
                "parameters": [
                    {
                        "description": "PublishMessageToUsers",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PublishMessageToUsers"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/users/{userId}/group-subscriptions": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupSubscriptions"
                ],
                "summary": "Clear group subscriptions by user id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.PublicErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/apierrors.ValidationErrorsResponse"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "apierrors.PublicErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "apierrors.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                }
            }
        },
        "apierrors.ValidationErrorsResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apierrors.ValidationErrorResponse"
                    }
                }
            }
        },
        "forms.CreateChannelSubscriptions": {
            "type": "object",
            "required": [
                "channelId",
                "userIds"
            ],
            "properties": {
                "channelId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.CreateDialogSubscriptions": {
            "type": "object",
            "required": [
                "initiatorId",
                "userIds"
            ],
            "properties": {
                "initiatorId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.CreateGroupSubscriptions": {
            "type": "object",
            "required": [
                "groupId",
                "userIds"
            ],
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.PublishMessageToChannel": {
            "type": "object",
            "required": [
                "channelId",
                "message"
            ],
            "properties": {
                "channelId": {
                    "type": "integer"
                },
                "message": {
                    "type": "object"
                }
            }
        },
        "forms.PublishMessageToGroup": {
            "type": "object",
            "required": [
                "groupId",
                "message"
            ],
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "message": {
                    "type": "object"
                }
            }
        },
        "forms.PublishMessageToInterlocutors": {
            "type": "object",
            "required": [
                "initiatorId",
                "message"
            ],
            "properties": {
                "initiatorId": {
                    "type": "integer"
                },
                "message": {
                    "type": "object"
                }
            }
        },
        "forms.PublishMessageToUsers": {
            "type": "object",
            "required": [
                "message",
                "userIds"
            ],
            "properties": {
                "message": {
                    "type": "object"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.RemoveChannelSubscriptions": {
            "type": "object",
            "required": [
                "channelId",
                "userIds"
            ],
            "properties": {
                "channelId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.RemoveDialogSubscriptions": {
            "type": "object",
            "required": [
                "initiatorId",
                "userIds"
            ],
            "properties": {
                "initiatorId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.RemoveGroupSubscriptions": {
            "type": "object",
            "required": [
                "groupId",
                "userIds"
            ],
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Websocket manager API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
